#!/bin/bash -e

sudo docker rmi -f rhvoice || true
rm -rf src

mkdir src
pushd .. > /dev/null
cp -r $(ls | grep -v docker | grep -v git) docker/src
popd > /dev/null
sudo docker build -t rhvoice .
sudo docker run rhvoice > /tmp/rhvoice.tar
sudo docker rmi -f rhvoice
