#!/bin/bash -ev

VER=1.2.3
KEY_NAME=dpkg1@luwrain.org

gpg --import dpkg1.*
rm -f dpkg1.*

mkdir rhvoice
cd rhvoice
cp -r /src $VER
cd $VER
dpkg-buildpackage -us -uc
cd ..
rm -rf $VER
mkdir -p dists/rhvoice/main/binary-amd64
mv *.deb dists/rhvoice/main/binary-amd64
dpkg-scanpackages dists/rhvoice/main/binary-amd64 /dev/null > dists/rhvoice/main/binary-amd64/Packages
cd dists
apt-ftparchive release . > Release
gpg --default-key $KEY_NAME --clearsign -o InRelease Release
cd ../..
tar -c rhvoice/ > rhvoice.tar
